[package]
name = "attributes"
version = "0.1.0"
edition = "2021"

[dependencies]
hax-lib-macros = { path = "../../hax-lib-macros" }
serde = { version = "1.0", features = ["derive"] }

[package.metadata.hax-tests]
into."fstar" = { snapshot = "none" }
