[package]
name = "hax-frontend-exporter"
version = { workspace = true }
edition = "2021"

[package.metadata.rust-analyzer]
rustc_private=true

[dependencies]
adt-into.workspace = true
serde.workspace = true
serde_json.workspace = true
schemars.workspace = true
itertools.workspace = true
hax-frontend-exporter-options.workspace = true
tracing.workspace = true
paste = "1.0.11"
