[package]
name = "hax-driver"
version = "0.1.0"
edition = "2021"

[package.metadata.rust-analyzer]
rustc_private = true

[[bin]]
path = "src/driver.rs"
name = "driver-hax-frontend-exporter"

[dependencies]
serde.workspace = true
serde_json.workspace = true
clap.workspace = true
hax-frontend-exporter.workspace = true
hax-cli-options.workspace = true
hax-cli-options-engine.workspace = true
hax-frontend-exporter-options.workspace = true
hax-lint.workspace = true
hax-diagnostics.workspace = true
itertools.workspace = true
const_format = "0.2"
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-tree.workspace = true
phase_debug_webapp.workspace = true
