[package]
name = "cli-lib"
version = "0.1.0"
edition = "2021"


[dependencies]
escape_string= "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
schemars = "0.8"
itertools = "0.10.5"
clap = { version = "4.0", features = ["derive"] }
paste = "1.0.11"
thir-export={path = "../thir-export"}
path-clean = "1.0.1"
tempfile = "3.4"

