[package]
name = "driver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
path = "src/cargo_thir_export.rs"
name = "cargo-thir-export"

[[bin]]
path = "src/driver_thir_export.rs"
name = "driver-thir-export"

[[bin]]
path = "src/json_schema.rs"
name = "thir-export-json-schema"

[dependencies]
escape_string= "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
schemars = "0.8"
itertools = "0.10.5"
clap = { version = "4.0", features = ["derive"] }
paste = "1.0.11"
thir-export={path = "../thir-export"}
path-clean = "1.0.1"

