[package]
name = "hax-cli-options-engine"
version = { workspace = true }
edition = "2021"

[dependencies]
serde.workspace = true
serde_json.workspace = true
schemars.workspace = true
itertools.workspace = true
clap.workspace = true
hax-diagnostics.workspace = true
hax-cli-options.workspace = true
hax-frontend-exporter.workspace = true
hax-frontend-exporter-options.workspace = true
path-clean = "1.0.1"

