[package]
name = "adt-into"
version = { workspace = true }
edition = "2021"

[lib]
proc-macro = true

[dependencies]
itertools.workspace = true
syn.workspace = true
proc-macro2 = "1.0"
quote = "1.0"

