name: Hacspec - Coq, SSProve Lib

on:
  schedule:
    - cron: '10 1 * * 0'
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    # the OS must be GNU/Linux to be able to use the docker-coq-action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'mathcomp/mathcomp:2.1.0-coq-8.18'
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up environment
        run: |
          echo "::group::Setting up problem matcher"
          echo "::add-matcher::./.github/coq-errors.json"
          echo "::endgroup::"
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'opam/coq-hacspec-ssprove.opam'
          custom_image: ${{ matrix.image }}
      - after_script: |
          startGroup "Run ssprove coq library tests"
            coqc ./tests/enum-repr/proofs/ssprove/extraction/Enum_repr.v
          endGroup "Run ssprove coq library tests"

# See also:
# https://github.com/coq-community/docker-coq-action#readme
# https://github.com/erikmd/docker-coq-github-action-demo
