[package]
name = "hax-diagnostics"
version = { workspace = true }
edition = "2021"

[package.metadata.rust-analyzer]
rustc_private=true

[dependencies]
serde.workspace = true
schemars.workspace = true
colored.workspace = true

